name = input("Enter the name 😊 :")
dob = input("enter the date of birth😁:")
city = input ("enter yout city:")
college = input("enter the college:")
Fav_food = input("enter the favorite food:")
Fav_animal =input("enter the favorite animal:")
Fav_movie = input("enter the favorites movies:")
Fav_song =input("enter favorites song:")
print(name,dob,city,college,Fav_food,Fav_animal,Fav_movie,Fav_song)